import { AuthContextProvider } from "@/context/AuthContext";
import { DialogContextProvider } from "@/context/DialogContext/DialogContextProvider";
import RootLayout from "@/layouts/RootLayout";

export const metadata = {
  title: "Next React Archetype",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <RootLayout>
      <AuthContextProvider>
        <DialogContextProvider>{children}</DialogContextProvider>
      </AuthContextProvider>
    </RootLayout>
  );
}
