import { AuthContextProvider } from "@/context/AuthContext";
import { DataContextProvider } from "@/context/DataContext";
import RootLayout from "@/layouts/RootLayout";

export const metadata = {
  title: "Next React Archetype",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <RootLayout>
      <AuthContextProvider>
        <DataContextProvider>{children}</DataContextProvider>
      </AuthContextProvider>
    </RootLayout>
  );
}
