version: "3.9"
services:

  app-frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=http://api-backend:3028
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/next.config.js:/app/next.config.js
    depends_on:
      - api-backend

  api-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3028:3028
    environment:
      DB_URL: mongodb://db/signings-data
    volumes:
      - ./backend/src:/app/app
    depends_on:
      - db
      
  db:
    image: mongo:6.0.6
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sergiogdev_admin
      MONGO_INITDB_ROOT_PASSWORD: password64683513830543
    volumes:
      - signings-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  signings-data: