version: "3.9"
services:
  app:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
  api:
    build: ./backend
    ports:
      - 3028:3028
    environment:
      DB_URL: mongodb://db/signings-data
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
  db:
    image: mongo:5.0.19-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sergiogdev_admin
      MONGO_INITDB_ROOT_PASSWORD: password64683513830543
    volumes:
      - signings-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  signings-data: